# app/core/schemas.py

from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

from app.core.config import get_settings

_limits = get_settings()

# ============================================================
# FINAL RESPONSE SCHEMA
# ============================================================


class Visualization(BaseModel):
    """Single visualization element"""

    type: str = Field(
        ..., description="Type: 'chart', 'diagram', 'table', or 'text'"
    )
    chart_data: Optional[Dict[str, Any]] = Field(
        None,
        description="Complete tool output from generate_chart. Include chart_json and summary.",
    )
    data: Optional[List[Dict[str, Any]]] = Field(
        None, description="Row data for tables"
    )
    content: Optional[str] = Field(
        None, description="Text content for text-type visualizations"
    )
    mermaid: Optional[str] = Field(
        None, description="Mermaid source for diagram-type visualizations"
    )
    caption: str = Field(
        ..., description="Brief explanation of what this visualization shows"
    )


class FinalResponseSchema(BaseModel):
    """Structured response schema for AI agent"""

    # Declared first because fields are generated in order, so naming the language is a
    # commitment made before a word of the answer exists. Four separate instructions to
    # match the user's language had already been ignored — an English question came back
    # answered entirely in Spanish, correct figures and all. A rule the model must restate
    # in its own output holds where a rule it merely reads does not.
    question_language: str = Field(
        ...,
        description=(
            "The language the user's question is written in, named in English — "
            "'English', 'Arabic', 'Spanish'. Decide this before writing anything else, "
            "then write every field below in that language."
        ),
        max_length=40,
    )
    answer: str = Field(
        ...,
        description="Natural language response, written in question_language and no other. Be conversational and insightful.",
        min_length=10,
    )
    visualizations: List[Visualization] = Field(
        default_factory=list,
        description="Charts/tables generated by tools. Empty list if none.",
        max_length=10,
    )
    key_insights: List[str] = Field(
        default_factory=list,
        description="3-5 concise bullet points (one sentence each) summarizing findings. Empty list if not applicable.",
        max_length=5,
    )
    # Asked for one site's cost per ticket, the agent applied the company-wide monthly rate
    # to that site's volume and said so unprompted — the single most useful sentence in the
    # answer, because the figure is defensible only with it. It did that once. A field makes
    # it routine: a substitution, an exclusion or a known data flaw belongs beside the
    # number it affects, not in a follow-up.
    assumptions: List[str] = Field(
        default_factory=list,
        description=(
            "What this answer rests on, one short sentence each. A substitution you made, "
            "rows you excluded, a data-quality flaw that affects the figures, or an "
            "ambiguity you resolved one way rather than another. Empty list if the numbers "
            "stand without qualification."
        ),
        max_length=5,
    )
    sources_used: List[str] = Field(
        default_factory=list,
        description="Filenames or table names actually referenced in this response. Empty list if none.",
    )


# ============================================================
# AGENT & API SCHEMAS
# ============================================================


class AgentStep(BaseModel):
    """Agent reasoning trace step"""

    type: str  # "reasoning" | "tool_call" | "tool_result"
    content: Optional[str] = None
    tool_name: Optional[str] = None
    tool_args: Optional[Dict] = None
    tool_result: Optional[str] = None


# session_id lands in Redis keys, so the charset is restricted rather than trusted. Shared
# by every endpoint that takes one: /upload validated nothing while /chat validated this,
# so a file could be uploaded under an id that could never be asked a question.
SESSION_ID_PATTERN = r"^[A-Za-z0-9_\-]+$"


class ChatRequest(BaseModel):
    session_id: Optional[str] = Field(
        None,
        max_length=_limits.MAX_SESSION_ID_CHARS,
        pattern=SESSION_ID_PATTERN,
    )
    query: str = Field(..., min_length=1, max_length=_limits.MAX_QUERY_CHARS)
    use_rag: bool = True
    model: Optional[str] = Field(None, max_length=64)


class ChatResponse(BaseModel):
    session_id: str
    response: str
    sources: List[str] = []
    metadata: Dict = {}
    agent_trace: List[AgentStep] = []


class UploadResponse(BaseModel):
    status: str
    session_id: str
    filename: str
    doc_id: str
    text_chunks: int
    dataframes: int


class FileInfo(BaseModel):
    filename: str
    doc_id: str
    uploaded_at: str
    text_chunks: int
    dataframes: int
    file_type: str


class ModelInfo(BaseModel):
    name: str
    provider: str
    is_default: bool = False


class ChatTurn(BaseModel):
    user: str
    assistant: str
    timestamp: str


class SessionStats(BaseModel):
    session_id: str
    chat_turns: int
    dataframes: int
    documents: int
    document_list: List[str] = []


class HistoryResponse(BaseModel):
    session_id: str
    history: List[ChatTurn]
    stats: SessionStats
