# app/core/schemas.py

from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

from app.core.config import get_settings

_limits = get_settings()

# ============================================================
# FINAL RESPONSE SCHEMA
# ============================================================


class Visualization(BaseModel):
    """Single visualization element"""

    type: str = Field(
        ..., description="Type: 'chart', 'diagram', 'table', or 'text'"
    )
    chart_data: Optional[Dict[str, Any]] = Field(
        None,
        description="Complete tool output from generate_chart. Include chart_json and summary.",
    )
    data: Optional[List[Dict[str, Any]]] = Field(
        None, description="Row data for tables"
    )
    content: Optional[str] = Field(
        None, description="Text content for text-type visualizations"
    )
    mermaid: Optional[str] = Field(
        None, description="Mermaid source for diagram-type visualizations"
    )
    caption: str = Field(
        ..., description="Brief explanation of what this visualization shows"
    )


class FinalResponseSchema(BaseModel):
    """Structured response schema for AI agent"""

    answer: str = Field(
        ...,
        description="Natural language response in the SAME language as user's query. Be conversational and insightful.",
        min_length=10,
    )
    visualizations: List[Visualization] = Field(
        default_factory=list,
        description="Charts/tables generated by tools. Empty list if none.",
        max_items=10,
    )
    key_insights: List[str] = Field(
        default_factory=list,
        description="3-5 concise bullet points (one sentence each) summarizing findings. Empty list if not applicable.",
        max_items=5,
    )
    sources_used: List[str] = Field(
        default_factory=list,
        description="Filenames or table names actually referenced in this response. Empty list if none.",
    )


# ============================================================
# AGENT & API SCHEMAS
# ============================================================


class AgentStep(BaseModel):
    """Agent reasoning trace step"""

    type: str  # "reasoning" | "tool_call" | "tool_result"
    content: Optional[str] = None
    tool_name: Optional[str] = None
    tool_args: Optional[Dict] = None
    tool_result: Optional[str] = None


class ChatRequest(BaseModel):
    # session_id lands in Redis keys, so the charset is restricted rather than trusted
    session_id: Optional[str] = Field(
        None,
        max_length=_limits.MAX_SESSION_ID_CHARS,
        pattern=r"^[A-Za-z0-9_\-]+$",
    )
    query: str = Field(..., min_length=1, max_length=_limits.MAX_QUERY_CHARS)
    use_rag: bool = True
    model: Optional[str] = Field(None, max_length=64)


class ChatResponse(BaseModel):
    session_id: str
    response: str
    sources: List[str] = []
    metadata: Dict = {}
    agent_trace: List[AgentStep] = []


class UploadResponse(BaseModel):
    status: str
    session_id: str
    filename: str
    doc_id: str
    text_chunks: int
    dataframes: int


class FileInfo(BaseModel):
    filename: str
    doc_id: str
    uploaded_at: str
    text_chunks: int
    dataframes: int
    file_type: str


class ModelInfo(BaseModel):
    name: str
    provider: str
    is_default: bool = False


class ChatTurn(BaseModel):
    user: str
    assistant: str
    timestamp: str


class SessionStats(BaseModel):
    session_id: str
    chat_turns: int
    dataframes: int
    documents: int
    document_list: List[str] = []


class HistoryResponse(BaseModel):
    session_id: str
    history: List[ChatTurn]
    stats: SessionStats
